/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

#ifndef _ATOMS_H_
#define _ATOMS_H_
#pragma once

#include "MP4.Atom.h"
#include "MP4.DataAtom.h"
#include "MP4.ContainerAtom.h"
#include "MP4.File.h"
#include "MP4.FullBox.h"
#include "MP4.UnknownAtom.h"
#include "MP4.BXML.h"
#include "MP4.CO64.h"
#include "MP4.CPRT.h"
#include "MP4.CTTS.h"
#include "MP4.DREF.h"
#include "MP4.ELST.h"
#include "MP4.FREE.h"
#include "MP4.FRMA.h"
#include "MP4.FTYP.h"
#include "MP4.HDLR.h"
#include "MP4.HMHD.h"
#include "MP4.IINF.h"
#include "MP4.ILOC.h"
#include "MP4.IMIF.h"
#include "MP4.IPMC.h"
#include "MP4.MDAT.h"
#include "MP4.MDHD.h"
#include "MP4.MEHD.h"
#include "MP4.MFHD.h"
#include "MP4.MFRO.h"
#include "MP4.MVHD.h"
#include "MP4.PADB.h"
#include "MP4.PDIN.h"
#include "MP4.PITM.h"
#include "MP4.SBGP.h"
#include "MP4.SCHI.h"
#include "MP4.SCHM.h"
#include "MP4.SDTP.h"
#include "MP4.SGPD.h"
#include "MP4.SMHD.h"
#include "MP4.STCO.h"
#include "MP4.STDP.h"
#include "MP4.STSC.h"
#include "MP4.STSD.h"
#include "MP4.STSH.h"
#include "MP4.STSS.h"
#include "MP4.STSZ.h"
#include "MP4.STTS.h"
#include "MP4.STZ2.h"
#include "MP4.SUBS.h"
#include "MP4.TFHD.h"
#include "MP4.TFRA.h"
#include "MP4.TKHD.h"
#include "MP4.TREF.h"
#include "MP4.TREX.h"
#include "MP4.TRUN.h"
#include "MP4.UDTA.h"
#include "MP4.VMHD.h"
#include "MP4.XML.h"

#endif /* _ATOMS_H_ */
